#!/usr/bin/env python3
"""
Generates src/components/Logo/paths.ts: the logo type set as outlines from
the self-hosted fonts (brief §4a), so the SVG logo needs no web font.

  MOTOR              Libre Franklin 900, tracking -0.035em, second O replaced by the mark
  CLAIMS DEPARTMENT  Public Sans 700, tracking ~0.01em, scaled so its width equals MOTOR's
  MCD                Libre Franklin 900, tracking -0.04em (the square)

Units: 1 em of the MOTOR line = 1000. Run: python3 scripts/logo-outlines.py
"""
import json
from pathlib import Path

from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen

ROOT = Path(__file__).resolve().parent.parent
FONTS = ROOT / "src" / "fonts"
OUT = ROOT / "src" / "components" / "Logo" / "paths.ts"

franklin = TTFont(FONTS / "libre-franklin-latin-900-normal.woff2")
public = TTFont(FONTS / "public-sans-latin-700-normal.woff2")


def glyph_name(font, ch):
    return font.getBestCmap()[ord(ch)]


def cap_height(font):
    return font["OS/2"].sCapHeight


def set_line(font, text, tracking_em, size):
    """Returns (paths, advance) at font size `size` (units), y-down, baseline at 0.
    paths: list of (glyph char, path string, x offset). Tracking is added after every glyph but the last."""
    upem = font["head"].unitsPerEm
    scale = size / upem
    glyphs = font.getGlyphSet()
    hmtx = font["hmtx"]
    x = 0.0
    out = []
    for i, ch in enumerate(text):
        name = glyph_name(font, ch)
        pen = SVGPathPen(glyphs, ntos=lambda v: f"{v:.1f}")
        # flip y (SVG is y-down) and scale to size
        tpen = TransformPen(pen, (scale, 0, 0, -scale, x, 0))
        glyphs[name].draw(tpen)
        d = pen.getCommands()
        if ch != " ":
            out.append({"ch": ch, "d": d, "x": round(x, 2)})
        adv = hmtx[name][0] * scale
        x += adv
        if i < len(text) - 1:
            x += tracking_em * size
    return out, x


def bounds(font, text, tracking_em, size):
    paths, adv = set_line(font, text, tracking_em, size)
    return adv


SIZE = 1000.0
motor, motor_width = set_line(franklin, "MOTOR", -0.035, SIZE)
cap = cap_height(franklin) * SIZE / franklin["head"].unitsPerEm

# The second O becomes the mark: keep its advance, drop its outline, record its centre and height.
second_o = [g for g in motor if g["ch"] == "O"][1]
o_name = glyph_name(franklin, "O")
gs = franklin.getGlyphSet()
from fontTools.pens.boundsPen import BoundsPen
bp = BoundsPen(gs)
gs[o_name].draw(bp)
xmin, ymin, xmax, ymax = bp.bounds
scale = SIZE / franklin["head"].unitsPerEm
o_h = (ymax - ymin) * scale
o_w = (xmax - xmin) * scale
mark_cx = second_o["x"] + (xmin + xmax) / 2 * scale
mark_cy = -(ymin + ymax) / 2 * scale
motor_paths = [g for g in motor if not (g["ch"] == "O" and g is second_o)]

# CLAIMS DEPARTMENT: scale so the advance width equals MOTOR's (measured to the last glyph's advance)
probe, probe_w = set_line(public, "CLAIMS DEPARTMENT", 0.01, SIZE)
line2_size = SIZE * motor_width / probe_w
line2, line2_w = set_line(public, "CLAIMS DEPARTMENT", 0.01, line2_size)
line2_cap = cap_height(public) * line2_size / public["head"].unitsPerEm

mcd, mcd_w = set_line(franklin, "MCD", -0.04, SIZE)

data = {
    "size": SIZE,
    "capHeight": round(cap, 2),
    "motor": {"paths": motor_paths, "width": round(motor_width, 2)},
    "mark": {"cx": round(mark_cx, 2), "cy": round(mark_cy, 2), "d": round(o_h, 2), "oWidth": round(o_w, 2)},
    "line2": {"paths": line2, "width": round(line2_w, 2), "size": round(line2_size, 2), "capHeight": round(line2_cap, 2)},
    "mcd": {"paths": mcd, "width": round(mcd_w, 2)},
}

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(
    "// Generated by scripts/logo-outlines.py from the self-hosted fonts. Do not edit.\n"
    "// Units: 1 em of the MOTOR line = 1000; baseline y = 0; y grows downwards.\n"
    f"export const logoPaths = {json.dumps(data, indent=2)} as const;\n"
)
print(f"MOTOR width {motor_width:.1f}, cap {cap:.1f}; mark d {o_h:.1f} at ({mark_cx:.1f},{mark_cy:.1f}); line2 size {line2_size:.1f} width {line2_w:.1f} cap {line2_cap:.1f}; MCD width {mcd_w:.1f}")
